### ISSUE TITLE
Feature Request: Add longest streak to hasher page

### ISSUE THREAD

**Issue by GoesDownDirty** [AlexThe81stGreatestEver/TheHashWebsite#16]
It would be neat for each hasher to be able to know what their longest hashing streak is.

**Comment by GoesDownDirty** [comment]
Barring any objection to this...I'd like to volunteer to work this one.

**Comment by GoesDownDirty** [comment]
I think this query computes the "maximum streak" for a specific hasher_ky:

SET @RUNNING_TOTAL:=0;
SELECT MAX(STREAK_COUNT)
  FROM (
SELECT SPECIAL_EVENT_DESCRIPTION, EVENT_DATE, ATTENDED,
       @RUNNING_TOTAL:=CASE WHEN ATTENDED=0 THEN 0 ELSE COALESCE(@RUNNING_TOTAL,0) + ATTENDED END AS STREAK_COUNT
  FROM (
SELECT HASHES.SPECIAL_EVENT_DESCRIPTION, HASHES.EVENT_DATE, COALESCE((
       SELECT 1
         FROM HASHINGS
        WHERE HASHINGS.HASH_KY=HASHES.HASH_KY
          AND HASHINGS.HASHER_KY=2736),0) AS ATTENDED
  FROM HASHES
 WHERE HASHES.KENNEL_KY=1987
 ORDER BY HASHES.EVENT_DATE) AS A) AS B

**Comment by GoesDownDirty** [comment]
Ok...I started over and I think I have something that works...try this out...

SET @PREV_HASHNUM:=-1;
SET @PREV_HASHER:=-1;
SET @ROWNUM:=0;
SET @RUNNING_COUNT:=0;
SELECT MAX_STREAK, HASHER_NAME
  FROM (
SELECT MAX(RUNNING_COUNT) AS MAX_STREAK, HASHER_KY
  FROM (
SELECT RUNNING_COUNT, HASHER_KY
  FROM (
SELECT @RUNNING_COUNT:=CASE WHEN PREV_HASHER!=HASHER_KY THEN 1
                            WHEN PREV_HASHNUM!=HASHNUM-1 THEN 1
                            ELSE @RUNNING_COUNT+1
                             END AS RUNNING_COUNT,
       PREV_HASHNUM, PREV_HASHER, HASHNUM, EVENT_DATE, HASH_KY, HASHER_KY
  FROM (
SELECT @PREV_HASHNUM AS PREV_HASHNUM, @PREV_HASHER AS PREV_HASHER, HASHNUM, EVENT_DATE, HASH_KY, HASHER_KY, @PREV_HASHNUM:=HASHNUM, @PREV_HASHER:=HASHER_KY
  FROM (
SELECT HASHES2.HASHNUM, HASHES2.EVENT_DATE, HASHES2.HASH_KY, HASHINGS.HASHER_KY
  FROM (
SELECT @ROWNUM:=@ROWNUM+1 AS HASHNUM, EVENT_DATE, HASH_KY
  FROM (
SELECT HASHES.EVENT_DATE, HASHES.HASH_KY
  FROM HASHES
 WHERE HASHES.KENNEL_KY=1987
 ORDER BY HASHES.EVENT_DATE) AS A) AS HASHES2
  JOIN HASHINGS
    ON HASHINGS.HASH_KY=HASHES2.HASH_KY
 ORDER BY HASHINGS.HASHER_KY, HASHES2.HASHNUM) AS B) AS C) AS D) AS E
 GROUP BY HASHER_KY) AS F
  JOIN HASHERS
    ON HASHERS.HASHER_KY=F.HASHER_KY
 ORDER BY 1 DESC

**Comment by AlexThe81stGreatestEver** [comment]
Added this feature
