### ISSUE TITLE
Feature Request: Add list of all-time longest streakers

### ISSUE THREAD

**Issue by GoesDownDirty** [AlexThe81stGreatestEver/TheHashWebsite#17]

**Comment by GoesDownDirty** [comment]
Here's my first attempt at writing a query for this:

SET @RUNNING_TOTAL:=0;
SET @PREV_HASHER_KEY:=0;
SELECT SPECIAL_EVENT_DESCRIPTION, EVENT_DATE, HASHER_KY, ATTENDED,
       @RUNNING_TOTAL:=CASE WHEN ATTENDED=0 OR EVENT_DATE=(
           SELECT MIN(EVENT_DATE) FROM HASHES WHERE KENNEL_KY=1987) 
       THEN 0 ELSE COALESCE(@RUNNING_TOTAL,0) + ATTENDED END AS STREAK_COUNT
  FROM (
SELECT HASHES.SPECIAL_EVENT_DESCRIPTION, HASHES.EVENT_DATE, 
       HASHERS.HASHER_KY, COALESCE((
       SELECT 1
         FROM HASHINGS
        WHERE HASHINGS.HASH_KY=HASHES.HASH_KY
          AND HASHINGS.HASHER_KY=HASHERS.HASHER_KY),0) AS ATTENDED
  FROM HASHES
 CROSS JOIN HASHERS
 WHERE HASHES.KENNEL_KY=1987
 ORDER BY HASHERS.HASHER_KY, HASHES.EVENT_DATE) AS A

It's failing with an out of memory error on our server.

@AlexThe81stGreatestEver  - does this work on your server or does it also throw an out of memory error?

**Comment by GoesDownDirty** [comment]
I think this query generates the list of longest streaks by hasher.
I was able to put the variable initialization in the innermost query to get around the issue with php only being able to issue a single query at a time.  I also cleaned up my original query a bit (which I originally attached to the wrong issue.) :)

SELECT MAX_STREAK, HASHER_NAME
  FROM (
SELECT MAX(RUNNING_COUNT) AS MAX_STREAK, HASHER_KY
  FROM (
SELECT RUNNING_COUNT, HASHER_KY
  FROM (
SELECT @RUNNING_COUNT:=CASE WHEN PREV_HASHER!=HASHER_KY THEN 1
                            WHEN PREV_HASHNUM!=HASHNUM-1 THEN 1
                            ELSE @RUNNING_COUNT+1
                             END AS RUNNING_COUNT,
       PREV_HASHNUM, PREV_HASHER, HASHNUM, HASH_KY, HASHER_KY
  FROM (
SELECT @PREV_HASHNUM AS PREV_HASHNUM, @PREV_HASHER AS PREV_HASHER, HASHNUM, HASH_KY, HASHER_KY, @PREV_HASHNUM:=HASHNUM, @PREV_HASHER:=HASHER_KY
  FROM (
SELECT HASHES2.HASHNUM, HASHES2.HASH_KY, HASHINGS.HASHER_KY
  FROM (
SELECT @ROWNUM:=@ROWNUM+1 AS HASHNUM, HASH_KY
  FROM (
SELECT HASHES.HASH_KY
  FROM HASHES,
       (SELECT @PREV_HASHNUM:=-1) v1,
       (SELECT @PREV_HASHER:=-1) v2,
       (SELECT @ROWNUM:=0) v3,
       (SELECT @RUNNING_COUNT:=0) v4
 WHERE HASHES.KENNEL_KY=1987
 ORDER BY HASHES.EVENT_DATE, HASHES.HASH_KY) AS A) AS HASHES2
  JOIN HASHINGS
    ON HASHINGS.HASH_KY=HASHES2.HASH_KY
 ORDER BY HASHINGS.HASHER_KY, HASHES2.HASHNUM) AS B) AS C) AS D) AS E
 GROUP BY HASHER_KY) AS HASHER_STREAK_COUNTS
  JOIN HASHERS
    ON HASHERS.HASHER_KY=HASHER_STREAK_COUNTS.HASHER_KY
 ORDER BY MAX_STREAK DESC, HASHER_NAME

**Comment by AlexThe81stGreatestEver** [comment]
Added in a page with this report
