### ISSUE TITLE
Feature Request: Add hash name/number to google map markers

### ISSUE THREAD

**Issue by GoesDownDirty** [AlexThe81stGreatestEver/TheHashWebsite#18]
I think the google map markers can be modified to display a popup when the mouse hovers over the marker.  It would be cool if the hash information for each marker was visible as a popup.

**Comment by AlexThe81stGreatestEver** [comment]
Agreed. That would be very cool.

**Comment by AlexThe81stGreatestEver** [comment]
I have delivered the changes. The markers now have a hover over message as well as an on-click action.
