### ISSUE TITLE
Feature Request: Make required hasher fields configurable

### ISSUE THREAD

**Issue by GoesDownDirty** [AlexThe81stGreatestEver/TheHashWebsite#19]
Currently first name, last name, and email address are required fields on the hasher input form.  It would be nice if these fields were either not required, or configurable (maybe through ProdConfig.php?)  DH3 users have requested that these fields be changed to be not required.

**Comment by AlexThe81stGreatestEver** [comment]
I agree. Great suggestion.

**Comment by GoesDownDirty** [comment]
Everyone seems fine with this as-is - closing.
