### ISSUE TITLE
Backsliders list for hash #1 is wonky

### ISSUE THREAD

**Issue by GoesDownDirty** [AlexThe81stGreatestEver/TheHashWebsite#28]
Maybe this link should be disabled for the first hash?

**Comment by GoesDownDirty** [comment]
Maybe it's wonky for #2 as well? Or is it working as expected?

**Comment by AlexThe81stGreatestEver** [comment]
It shows first timers with a pink color. Because everyone is a first timer at the first hash, it shows everyone in pink without explaining what pink means. Adding an explanation to the page would probably suffice.

**Comment by AlexThe81stGreatestEver** [comment]
Wrote a new backsliders page. The new page has a fluid layout (has different layout depending on screen size) and makes is clear if this is someone's first hash.
